CREATE DATABASE DBEX2;
USE DBEX2;

CREATE TABLE NIVEL(
	IDNIVEL INT NOT NULL PRIMARY KEY ,
	DESCRICAO VARCHAR(100),           
);

CREATE TABLE USUARIO(
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100),
	EMAIL VARCHAR(150),
	SENHA VARCHAR(20), 
	IDNIVEL INT NOT NULL,
	FOREIGN KEY (IDNIVEL) REFERENCES NIVEL (IDNIVEL) 
);

INSERT INTO NIVEL(DESCRICAO) VALUES ('Administrador');
INSERT INTO NIVEL(DESCRICAO) VALUES ('Normal');
