DROP DATABASE IF EXISTS  DBEX2;
CREATE DATABASE DBEX2;
USE DBEX2;

CREATE TABLE NIVEL(
	IDNIVEL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(100),
	FLAGATIVA BOOLEAN             
);

CREATE TABLE USUARIOVO(
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100),
	EMAIL VARCHAR(150),
	SENHA VARCHAR(20),
	IDNIVEL INT NOT NULL,
	FOREIGN KEY (IDNIVEL) REFERENCES NIVEL (IDNIVEL) 
);